=== RePlay-DH/replay-dh-client/src/main/resources/bwfdm/replaydh/ui/actions/action-list.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
   The action_attributes parameter entity is a convenient representation
   of the common attributes between an action and an action-list.

   template - a reference to a previously defined action. 
           
   type - if the value is "single" then the action represents a command
          action. If the value is "toggle" then the action is a multi-state
          action which may be selected or unselected. This value is
          "single" by default.
    
   name - the label for the action. Will be used as a localization key.
   			If no localization value could be found for a key, the name
   			string will be used in its raw form.

   mnemonic - the mnemonic to use for the action. Should be a single character.

   icon - the relative path to an image in the classpath that represents
            a small icon.
            
   sicon - the relative path to an image in the classpath that represents
            a small icon used as selected icon in toggle actions.

   licon - the relative path to an image in the classpath that represents a large icon.
   
   slicon - the relative path to an image in the classpath that represents a large icon
   			used as selected icon in toggle actions.
   

   desc - a short description of the action. Used for localization with the same
   			rules as the name attribute.
   			
   virtual - marks an action definition to serve as a template. Templates cannot be 
   			instantiated as actions directly but rather actions can be derived from
   			them. This way an application can define templates with attributes for
   			commonly used actions like 'copy', 'cut' and so on and then derive
   			specialized actions for different usages like 'copyEditorContent' without
   			the need to redefine all attributes for each derived action.
   			
   command - a string passed as action command to events created by the action. Can
   			be used to distinguish between multiple actions handled by the same
   			callback method.
    
   accel - a string that represents the keyboard accelerator to invoke
           the action. The string should be formatted according to the syntax
           outlined in the javadoc for the static method:

                     javax.swing.KeyStroke#getKeyStroke(String)

           For example, the string "control S" represents the Control-S key.
-->

<!ENTITY % action_attributes "idref     CDATA #IMPLIED
          template      CDATA #IMPLIED
          type      (single | toggle) #IMPLIED
          name      CDATA #IMPLIED
          mnemonic  CDATA #IMPLIED
          icon    CDATA #IMPLIED
          sicon    CDATA #IMPLIED
          licon      CDATA #IMPLIED
          slicon      CDATA #IMPLIED
          desc      CDATA #IMPLIED
          virtual	(true | false) #IMPLIED
          command    CDATA #IMPLIED
          accel     CDATA #IMPLIED"
>

<!ELEMENT actions (action | action-list | action-set)*>

<!-- 
    An action-set is an ordered collection of actions
    and grouping informations. 
-->

<!ELEMENT action-set (action | group)*>
<!ATTLIST action-set id ID #REQUIRED>

<!-- 
    The action element represents the properties of a javax.swing.Action. 
    This element can be a placeholder for an action within an action-set
    or action-list.
    
    id - a unique id for the action.

    The idref attribute should be used instead of the id attribute if an action 
    refers to a previous action definition. An action with both an id and 
    idref is undefined.

    See the desciption for the action_attributes entity for a detailed
    description of the rest of the attributes.

-->

<!ELEMENT action EMPTY>
<!ATTLIST action 
          id        ID #IMPLIED
          %action_attributes;
>


<!--
    The action-list is used to define lists and trees of actions.
    These can map to toolbars, menus and popups. Note that the list
    itself might define another action as well. This action is typically
    used to 'activate' the component constructed from the list information.

    See the desciption for the action_attributes entity for a detailed
    description of the rest of the attributes.
-->

<!ELEMENT action-list (item | action | group | action-set | action-list | separator | empty)*>
<!ATTLIST action-list
          id        ID #REQUIRED
          %action_attributes;
>


<!--
    The item elements describes a single entry in an action-list
    Type attribute format and its handling:
    
    action:			Id used to resolve actual action instance to be
    				placed at the component
    action-list:	Id used to resolve an action-list that will be
    				inserted. The way this "insertion" is done depends
    				on the component being created. A menu will typically
    				be layed out hierarchically whereas a tool-bar will 
    				have nested action-lists "inlined".
    action-set:		Id to resolve a collection of actions to be inserted
    label:			String or localization key that is used on a JLabel
    custom:			Value treated as placeholder that is passed to the
    				'properties' map to fetch the object to be inserted.
    				This replacement object can be of the following types:
    				String - Displayed via JLabel
    				Action - Inserted at position of 'custom' element
    				ActionSet - Inserted at position of 'custom' element
    				ActionList - Inserted at position of 'custom' element
    				Component - Added to the container being populated
    				If the replacement object is an array its elements will 
    				be iterated and handled one by one according to the above
    				scheme. Note that is not possible to embed additional
    				arrays within the single replacement array.
    separator:		Call to the containers 'addSeparator()' method. Some
    				containers allow for the 'size' of the separator to be
    				specified. For such a container the 'value' attribute is
    				being interpreted as either a numerical width or one of
    				'small', 'medium', 'wide' with an implementation
    				specific mapping to actual separator width values.
    empty:			Places an empty placeholder at the current position (using 'value' as width).
    glue:			Inserts a 'glue' component, i.e. a component that expands
    				automatically to consume free space. This item type is not
    				supported by all action components. Usually only tool-bar
    				components make use of this.
-->

<!ELEMENT item EMPTY>
<!ATTLIST item
          type      (action|action-list|action-set|label|custom|separator|empty|glue) #REQUIRED
          value		CDATA #IMPLIED
>

<!--
    Generates a group of actions with a mutually exclusive selection state.
    Typically components generated for those actions are JToggleButton or
    JRadioButtonMenuItem instances. 
    
    All actions defined or referenced within a group element should have 
    their type attribute set to 'toggle'.
-->

<!ELEMENT group (action)*>
<!ATTLIST group
          id        CDATA #REQUIRED
>

<!--
    Shortform for an item element with its type attribute set to 'separator'
-->

<!ELEMENT separator EMPTY>

<!--
    Shortform for an item element with its type attribute set to 'empty'
-->

<!ELEMENT empty EMPTY>

=== RePlay-DH/replay-dh-client/src/main/resources/bwfdm/replaydh/ui/workflow/graph/workflow-graph-actions.xml
<?xml version="1.0" ?>
<!DOCTYPE actions SYSTEM "action-list.dtd">
<actions>

	<!--
		WORKSPACE GRAPH
	-->
	
	<!-- Load Dummy Graph -->
	<action id="replaydh.ui.core.workflowGraph.loadDummyGraph"
		name="${id}.name" desc="${id}.description" icon="icons8-bug-40.png" />
	
	<!-- Refresh Graph -->
	<action id="replaydh.ui.core.workflowGraph.refreshGraph"
		name="${id}.name" desc="${id}.description" icon="refresh.gif" help="true" />
	
	<!-- Change Active Step -->
	<action id="replaydh.ui.core.workflowGraph.changeActiveStep"
		name="${id}.name" desc="${id}.description" icon="navi_down.png" help="true" />
	
	<!-- Focus Active Step -->
	<action id="replaydh.ui.core.workflowGraph.focusActiveStep"
		name="${id}.name" desc="${id}.description" icon="compress.gif" help="true" />
		
	<!-- Compress Step -->
	<action id="replaydh.ui.core.workflowGraph.compressStep"
		name="${id}.name" desc="${id}.description" icon="collapseall.gif" help="true" />
		
	<!-- Expand Step -->
	<action id="replaydh.ui.core.workflowGraph.expandStep"
		name="${id}.name" desc="${id}.description" icon="expandall.gif" help="true" />
		
	<!-- Export Step Metadata -->
	<action id="replaydh.ui.core.workflowGraph.exportStepMetadata"
		name="${id}.name" desc="${id}.description" icon="externalize.gif" help="true" />
		
	<!-- Export Step Resources -->
	<action id="replaydh.ui.core.workflowGraph.exportStepResources"
		name="${id}.name" desc="${id}.description" icon="export_wiz.gif" help="true" />
		
	<!-- Export Metadata -->
	<action id="replaydh.ui.core.workflowGraph.exportMetadata"
		name="${id}.name" desc="${id}.description" icon="externalize.gif" help="true" />
		
	<!-- Export Resources -->
	<action id="replaydh.ui.core.workflowGraph.exportResources"
		name="${id}.name" desc="${id}.description" icon="export_wiz.gif" help="true" />
		
	<!-- Import Repository -->
	<action id="replaydh.ui.core.workflowGraph.updateRepository"
		name="${id}.name" desc="${id}.description" icon="import_wiz.gif" help="true" />
		
	<!-- Publish Resources -->
	<!-- 
		<action id="replaydh.ui.core.workflowGraph.publishResources"
		name="${id}.name" desc="${id}.description" icon="icons8-epub-40.png"/>
	 -->
	
	<!-- Toggle Compress Pipes -->
	<action id="replaydh.ui.core.workflowGraph.toggleCompressPipes"
		name="${id}.name" desc="${id}.description" icon="collapseall.gif" 
		sicon="expandall.gif" type="toggle" help="true" />
		
	<!-- ToolBar List for header area -->
	<action-list id="replaydh.ui.core.workflowGraph.toolBarList">
		<!-- <item type="label" value="replaydh.panels.workflowGraph.title" /> -->
		<item type="custom" value="workflowTitle" />
		<item type="glue" />
		<item type="action" value="replaydh.ui.core.workflowGraph.exportMetadata" />
		<item type="action" value="replaydh.ui.core.workflowGraph.exportResources" />
		<item type="action" value="replaydh.ui.core.workflowGraph.updateRepository" />
		<separator />
		<action-list id="replaydh.ui.core.workflowGraph.publishResources" help="true"
			name="${id}.name" desc="${id}.description" icon="icons8-epub-40.png">
			<item type="custom" value="publisherExtensions" />
		</action-list>
		<separator />
		<item type="action" value="replaydh.ui.core.workflowGraph.changeActiveStep" />
		<item type="action" value="replaydh.ui.core.workflowGraph.focusActiveStep" />
		<separator />
		<item type="action" value="replaydh.ui.core.workflowGraph.toggleCompressPipes" />
		<separator />
		
		<!--  
		<item type="action" value="replaydh.ui.core.workflowGraph.loadDummyGraph" />
		<separator />
		-->
		<item type="action" value="replaydh.ui.core.workflowGraph.refreshGraph" />
	</action-list>
	
	<action-list id="replaydh.ui.core.workflowGraph.popupMenuList">
		<item type="action" value="replaydh.ui.core.workflowGraph.changeActiveStep" />
		<separator />
		<item type="action" value="replaydh.ui.core.workflowGraph.compressStep" />
		<item type="action" value="replaydh.ui.core.workflowGraph.expandStep" />
		<separator />
		<item type="action" value="replaydh.ui.core.workflowGraph.exportStepMetadata" />
		<item type="action" value="replaydh.ui.core.workflowGraph.exportStepResources" />
		<!-- 
		<separator />
		<item type="action" value="replaydh.ui.core.workflowGraph.exportMetadata" />
		<item type="action" value="replaydh.ui.core.workflowGraph.exportResources" />
		 -->
	</action-list>
	
</actions>

=== RePlay-DH/replay-dh-client/src/main/resources/bwfdm/replaydh/ui/workflow/workspace-tracker-panel-actions.xml
<?xml version="1.0" ?>
<!DOCTYPE actions SYSTEM "action-list.dtd">
<actions>

	<!--
		WORKSPACE TRACKER PANEL
	-->
	
	<!-- Create Dummy File -->
	<action id="replaydh.ui.core.workspaceTrackerPanel.createDummyFile"
		name="${id}.name" desc="${id}.description" icon="add_obj.gif" />
	
	<!-- Edit Dummy File -->
	<action id="replaydh.ui.core.workspaceTrackerPanel.editDummyFile"
		name="${id}.name" desc="${id}.description" icon="write_obj.gif" />
	
	<!-- Delete Dummy File -->
	<action id="replaydh.ui.core.workspaceTrackerPanel.deleteDummyFile"
		name="${id}.name" desc="${id}.description" icon="delete_obj.gif" />
	<!-- ToolBar List for header area -->
	<action-list id="replaydh.ui.core.workspaceTrackerPanel.toolBarList">
		<item type="label" value="replaydh.panels.workspaceTracker.title" />
		<item type="glue" />
		<item type="action" value="replaydh.ui.core.workspaceTrackerPanel.createDummyFile" condition="global:debug" />
		<item type="action" value="replaydh.ui.core.workspaceTrackerPanel.deleteDummyFile" condition="global:debug" />
		<item type="action" value="replaydh.ui.core.workspaceTrackerPanel.editDummyFile" condition="global:debug" />
	</action-list>
	
</actions>

=== RePlay-DH/replay-dh-client/src/main/resources/bwfdm/replaydh/ui/actions/default-actions.xml
<?xml version="1.0" ?>
<!DOCTYPE actions SYSTEM "action-list.dtd">
<actions>

	<!--
		SHARED TEMPLATES
	-->
	
	<!-- Copy -->
	<action id="actions.default.copyAction" virtual="true"
		name="actions.text.copy-to-clipboard.name" 
		desc="actions.text.copy-to-clipboard.description" 
		icon="copy_edit.gif" 
		accel="control C" 
		command="copy" />
	
	<!-- Cut -->
	<action id="actions.default.cutAction" virtual="true"
		name="actions.text.cut-to-clipboard.name" 
		desc="actions.text.cut-to-clipboard.description" 
		icon="cut_edit.gif" 
		accel="control X" 
		command="cut" />
	
	<!-- Paste -->
	<action id="actions.default.pasteAction" virtual="true"
		name="actions.text.paste-from-clipboard.name" 
		desc="actions.text.paste-from-clipboard.description" 
		icon="paste_edit.gif" 
		accel="control V" 
		command="paste" />
	
	<!-- Clear -->
	<action id="actions.default.clearAction" virtual="true"
		name="actions.text.clear.name" 
		desc="actions.text.clear.description" 
		icon="clear_co.gif" 
		accel="escape" 
		command="clear" />
	
	<!-- Select ALl -->
	<action id="actions.default.selectAllAction" virtual="true"
		name="actions.text.select-all.name" 
		desc="actions.text.select-all.description" 
		icon="select.gif" 
		accel="control A"
	 	command="select-all" />
	
	<!-- Undo -->
	<action id="actions.default.undoAction" virtual="true"
		name="actions.text.undo.name" 
		desc="actions.text.undo.description" 
		icon="undo_edit.gif" 
		accel="control Z"
	 	command="undo" />
	
	<!-- Redo -->
	<action id="actions.default.redoAction" virtual="true"
		name="actions.text.redo.name" 
		desc="actions.text.redo.description" 
		icon="redo_edit.gif"
		accel="control Y"
	 	command="redo" />
	
	<!-- Expand All -->
	<action id="actions.default.expandAllAction" virtual="true"
		name="actions.tree.expandAll.name" 
		desc="actions.tree.expandAll.description"
		icon="expandall.gif" />
	
	<!-- Collapse All -->
	<action id="actions.default.collapseAllAction" virtual="true"
		name="actions.tree.collapseAll.name" 
		desc="actions.tree.collapseAll.description" 
		icon="collapseall.gif" />
	
	<!-- Add -->
	<action id="actions.default.addAction" virtual="true"
		name="actions.default.add" 
		desc="actions.default.add" 
		icon="add_obj.gif"
		command="add" />
	
	<!-- Remove -->
	<action id="actions.default.removeAction" virtual="true"
		name="actions.default.remove" 
		desc="actions.default.remove" 
		icon="delete_obj.gif"
		command="remove" />
	
	<!-- Edit -->
	<action id="actions.default.editAction" virtual="true"
		name="actions.default.edit" 
		desc="actions.default.edit"
		icon="write_obj.gif"
		command="edit" />
	
	<!-- Open -->
	<action id="actions.default.openAction" virtual="true"
		name="actions.default.open" 
		desc="oactions.default.pen"
		command="open" />
	
	<!-- Close -->
	<action id="actions.default.closeAction" virtual="true"
		name="actions.default.close" 
		desc="actions.default.close"
		command="close" />
	
	<!-- Rename -->
	<action id="actions.default.renameAction" virtual="true"
		name="actions.default.rename" 
		desc="actions.default.rename" 
		icon="wordassist_co.gif" 
		command="rename" />
	
	<!-- Inspect -->
	<action id="actions.default.inspectAction" virtual="true"
		name="actions.default.inspect" 
		desc="actions.default.inspect"
		icon="insp_sbook.gif"
		command="inspect" />
	
	<!-- Print -->
	<action id="actions.default.printAction" virtual="true"
		name="actions.default.print" 
		desc="actions.default.print"
		icon="print_edit.gif" 
		command="print" />
	
	<!-- Clone -->
	<action id="actions.default.cloneAction" virtual="true"
		name="actions.default.clone" 
		desc="actions.default.clone"
		icon="breakpoint_view.gif"
		command="clone" />
	
	<!-- Open Preferences -->
	<action id="actions.default.openPreferencesAction" virtual="true"
		name="sharedActions.openPreferences.name" 
		desc="sharedActions.openPreferences.description"
		icon="settings.gif" 
		command="preferences" />
	
	<!-- Load -->
	<action id="actions.default.loadAction" virtual="true"
		name="actions.default.load" 
		desc="actions.default.load"
		icon="fldr_obj.gif" 
		command="load" />
	
	<!-- Execute -->
	<action id="actions.default.executeAction" virtual="true"
		name="actions.default.execute" 
		desc="actions.default.execute"
		icon="nav_go.gif" 
		command="execute" />
	
	<!-- Zoom In -->
	<action id="actions.default.zoomInAction" virtual="true"
		name="actions.default.zoomIn" 
		desc="actions.default.zoomIn"
		icon="zoomin.gif"
		command="zoom-in" />
	
	<!-- Zoom Out -->
	<action id="actions.default.zoomOutAction" virtual="true"
		name="actions.default.zoomOut" 
		desc="actions.default.zoomOut"
		icon="zoomout.gif" 
		command="zom-out" />
	
	<!-- Zoom -->
	<action id="actions.default.zoomAction" virtual="true"
		name="actions.default.zoom" 
		desc="actions.default.zoom"
		icon="zoom.gif"
		command="zoom" />
	
	<!-- Refresh -->
	<action id="actions.default.refreshAction" virtual="true"
		name="actions.default.refresh" 
		desc="actions.default.refresh"
		icon="nav_refresh.gif"
		command="refresh" />
	
	<!-- Save -->
	<action id="actions.default.saveAction" virtual="true"
		name="actions.default.save" 
		desc="actions.default.save"
		icon="save_edit.gif" 
		command="save" />
	
	<!-- Save As -->
	<action id="actions.default.saveAsAction" virtual="true"
		name="actions.default.saveAs" 
		desc="actions.default.saveAs"
		icon="saveas_edit.gif"
		command="save-as" />
	
	<!-- New -->
	<action id="actions.default.newAction" virtual="true"
		name="actions.default.new" 
		desc="actions.default.new"
		icon="new_icon.gif"
		command="new" />
	
	<!-- Import -->
	<action id="actions.default.importAction" virtual="true"
		name="actions.default.import" 
		desc="actions.default.import"
		icon="import_wiz.gif"
		command="import" />
	
	<!-- Export -->
	<action id="actions.default.exportAction" virtual="true"
		name="actions.default.export" 
		desc="actions.default.export"
		icon="export_wiz.gif"
		command="export" />
	
	<!-- Filter -->
	<action id="actions.default.filterAction" virtual="true"
		name="actions.default.filter" 
		desc="actions.default.filter"
		icon="filter_apply.png"
		command="filter" />
	
	<!-- Clear Filter -->
	<action id="actions.default.clearFilterAction" virtual="true"
		name="actions.default.clearFilter" 
		desc="actions.default.clearFilter"
		icon="filter_reset.png" 
		command="clear-filter" />
	
	<!-- First Element -->
	<action id="actions.default.firstElementAction" virtual="true"
		name="actions.navigation.first.name" 
		desc="actions.navigation.first.description"
		icon="navi_left_stop.png"
		command="firstElement" />

	<!-- Previous Element -->
	<action id="actions.default.previousElementAction" virtual="true"
		name="actions.navigation.previous.name" 
		desc="actions.navigation.previous.description"
		icon="navi_left.png"
		command="previousElement" />
 
	<!-- Next Element -->
	<action id="actions.default.nextElementAction" virtual="true"
		name="actions.navigation.next.name" 
		desc="actions.navigation.next.description"
		icon="navi_right.png"
		command="nextElement" />
 
	<!-- Last Element -->
	<action id="actions.default.lastElementAction" virtual="true"
		name="actions.navigation.last.name" 
		desc="actions.navigation.last.description"
		icon="navi_right_stop.png"
		command="lastElement" />
 
	<!-- Start Media -->
	<action id="actions.default.startAction" virtual="true"
		name="actions.media.start.name" 
		desc="actions.media.start.description"
		icon="media_playback_start.png"
		command="start" />
 
	<!-- Stop Media -->
	<action id="actions.default.stopAction" virtual="true"
		name="actions.media.stop.name" 
		desc="actions.media.stop.description"
		icon="media_playback_stop.png"
		command="stop" />
 
	<!-- Pause Media -->
	<action id="actions.default.pauseAction" virtual="true"
		name="actions.media.pause.name" 
		desc="actions.media.pause.description"
		icon="media_playback_pause.png"
		command="pause" />	

</actions>

=== RePlay-DH/replay-dh-client/src/main/resources/bwfdm/replaydh/ui/metadata/metadata-manager-panel-actions.xml
<?xml version="1.0" ?>
<!DOCTYPE actions SYSTEM "action-list.dtd">
<actions>

	<!--
		METADATA MANAGER PANEL
	-->
	
	<!-- Add Record -->
	<action id="replaydh.ui.core.metadataManagerPanel.addRecord"
		name="${id}.name" desc="${id}.description" icon="data-add-icon.png" />
	
	<!-- Edit Record -->
	<action id="replaydh.ui.core.metadataManagerPanel.editRecord"
		name="${id}.name" desc="${id}.description" icon="data-edit-icon.png" />
	
	<!-- Remove Record -->
	<action id="replaydh.ui.core.metadataManagerPanel.removeRecord"
		name="${id}.name" desc="${id}.description" icon="data-delete-icon.png" />
	
		
	<!-- ToolBar List for header area -->
	<action-list id="replaydh.ui.core.metadataManagerPanel.toolBarList">
		<item type="label" value="replaydh.ui.core.metadataManagerPanel.selectedRepository" />
		<item type="custom" value="selector" />
		<item type="glue" />
	</action-list>
	
</actions>

=== RePlay-DH/replay-dh-client/src/main/resources/bwfdm/replaydh/ui/core/main-panel-actions.xml
<?xml version="1.0" ?>
<!DOCTYPE actions SYSTEM "action-list.dtd">
<actions>

	<!--
		MAIN PANEL
	-->
	
	<!-- Add Step -->
	<action id="replaydh.ui.core.mainPanel.addStep"
		name="${id}.name" desc="${id}.description" licon="record-step.png" />
	
	<!-- Update Status -->
	<action id="replaydh.ui.core.mainPanel.updateStatus"
		name="${id}.name" desc="${id}.description" icon="refresh.gif" licon="update-icon.png" />
	
	<!-- Cancel Update -->
	<action id="replaydh.ui.core.mainPanel.cancelUpdate"
		name="${id}.name" desc="${id}.description" icon="stop.gif" licon="stop-icon.png" />
	
	<!-- Toggle Tracker Active -->
	<action id="replaydh.ui.core.mainPanel.toggleTrackerActive" type="toggle"
		name="${id}.name" desc="${id}.description" icon="media_playback_start.png" 
		licon="stopwatch-start-icon.png" sicon="media_playback_stop.png" slicon="stopwatch-finish-icon.png" />
	
	<!-- Toggle Details -->
	<action id="replaydh.ui.core.mainPanel.toggleDetails"
		name="${id}.name" desc="${id}.description" />
	
	<!-- Change Workspace -->
	<action id="replaydh.ui.core.mainPanel.changeWorkspace"
		name="${id}.name" desc="${id}.description" licon="Documents-icon.png" />
	
	<!-- Import Workflow Schema -->
	<action id="replaydh.ui.core.mainPanel.importWorkflowSchema"
		name="${id}.name" desc="${id}.description" />
	
	<!-- Open Workspace Folder -->
	<action id="replaydh.ui.core.mainPanel.openWorkspaceFolder"
		name="${id}.name" desc="${id}.description" icon="fldr_obj.gif" />
	
	<!-- Clear Resource Cache -->
	<action id="replaydh.ui.core.mainPanel.clearResourceCache"
		name="${id}.name" desc="${id}.description" icon="clear_co.gif" />
	
	<!-- ToolBar List for header area -->
	<action-list id="replaydh.ui.core.mainPanel.menuBarList">
		<action-list id="replaydh.ui.core.mainPanel.menuBarList.file" name="${id}.name">
			<item type="action" value="replaydh.ui.core.mainPanel.changeWorkspace" />
			<item type="action" value="replaydh.ui.core.mainPanel.importWorkflowSchema" />
			<separator />
			<item type="action" value="replaydh.ui.core.mainPanel.openWorkspaceFolder" />
			<separator />
			<action id="replaydh.ui.core.mainPanel.exit" name="${id}.name" desc="${id}.description" />
		</action-list>
		<action-list id="replaydh.ui.core.mainPanel.menuBarList.window" name="${id}.name">
			<action id="replaydh.ui.core.mainPanel.showMetadataManager" name="${id}.name" desc="${id}.description" />
			<separator/>
			<item type="action" value="replaydh.ui.core.mainPanel.toggleDetails" />
		</action-list>
		<action-list id="replaydh.ui.core.mainPanel.menuBarList.help" name="${id}.name">
			<action id="replaydh.ui.core.mainPanel.about" name="${id}.name" desc="${id}.description" />
		</action-list>
	</action-list>
	
</actions>
