=== RePlay-DH/replay-dh-client/src/main/resources/bwfdm/replaydh/workflow/schema/Workflow.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		targetNamespace="https://www.ub.uni-stuttgart.de/replay/Workflow"
		xmlns:wfl="https://www.ub.uni-stuttgart.de/replay/Workflow" 
		xmlns:cmn="https://www.ub.uni-stuttgart.de/replay/CommonTypes" 
		attributeFormDefault="unqualified"
		elementFormDefault="qualified">
		
	<xsd:import schemaLocation="https://www.ub.uni-stuttgart.de/replay/CommonTypes CommonTypes.xsd" 
		namespace="https://www.ub.uni-stuttgart.de/replay/CommonTypes" />
		
	<xsd:element name="workflowSchema">
		
        <xsd:annotation>
			<xsd:documentation></xsd:documentation>
		</xsd:annotation>
        
        <xsd:complexType>
			<xsd:sequence minOccurs="0">
				<xsd:element name="personIdentifiers" type="wfl:identifierSchemaType">
					<xsd:annotation>
						<xsd:documentation>Specification of supported types for identifying persons</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="resourceIdentifiers" type="wfl:identifierSchemaType">
					<xsd:annotation>
						<xsd:documentation>Specification of supported types for identifying resources</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="resourceTypes" type="wfl:labelSchemaType">
					<xsd:annotation>
						<xsd:documentation>Specification of supported labels for resource types</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="roles" type="wfl:labelSchemaType">
					<xsd:annotation>
						<xsd:documentation>Specification of supported roles for human workflow participants</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="id" type="cmn:simpleIdentifierAttr" use="required">
				<xsd:annotation>
					<xsd:documentation>The globally unique identifier for this schema. Note that the internal identifier for the default schema "replay-dh.workflow.schema.default" is reserved!</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="description" type="xsd:string" use="optional">
				<xsd:annotation>
					<xsd:documentation>Optional human readable description of the schema</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="localize" type="xsd:boolean" use="optional">
				<xsd:annotation>
					<xsd:documentation>If set to "true" all name and/or description fields will be treated as localization keys.</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="useDefaultLocalizationSuffixes" type="xsd:boolean" use="optional">
				<xsd:annotation>
					<xsd:documentation>If set to "true", all localization keys will be suffixed with their respective default suffixes. Those are ".name" for the name key and ".description" for the description property.</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="localizationRoot" type="xsd:string" use="optional">
				<xsd:annotation>
					<xsd:documentation>Optional localization prefix to simplify definition of loca keys in the schema. If this attribute is present, all loca keys defined in sub-elements will be prefixed by the value. Ignored if the "localize" attribute is set to "false".</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
    </xsd:element>
		
	<xsd:complexType name="identifierSchemaType">
		<xsd:annotation>
			<xsd:documentation>Specification of identifier types supported in a certain context</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="identifierType" type="wfl:identifierTypeType" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>Identifier types supported by this schema</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="defaultIdentifierType" type="cmn:simpleIdentifierAttr">
			<xsd:annotation>
				<xsd:documentation>Optional marker for a declared label to be preferred</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="allowCustomIdentifierTypes" type="xsd:boolean">
			<xsd:annotation>
				<xsd:documentation>Flag to indicate whether additional identifier types are allowed</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
		
	<xsd:complexType name="labelSchemaType">
		<xsd:annotation>
			<xsd:documentation>Specification of descriptive labels for a certain context</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="label" type="wfl:labelType" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>Main-labels for this schema</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="defaultLabel" type="cmn:simpleIdentifierAttr">
			<xsd:annotation>
				<xsd:documentation>Optional marker for a declared label to be preferred</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="allowCustomLabels" type="xsd:boolean">
			<xsd:annotation>
				<xsd:documentation>Flag to indicate whether additional labels are allowed</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="allowCompoundLabels" type="xsd:boolean">
			<xsd:annotation>
				<xsd:documentation>Flag to indicate whether this schema supports compound labels</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="compoundSeparator" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation>Optional separator used for constructing compound labels</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="labelType">
		<xsd:annotation>
			<xsd:documentation>Basic label definition with support for localization</xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="cmn:simpleLabelType">
				<xsd:sequence>
					<xsd:element name="subLabels" minOccurs="0" maxOccurs="1">
						<xsd:annotation>
							<xsd:documentation>List of legal sub-labels for this label</xsd:documentation>
						</xsd:annotation>
						<xsd:complexType>
							<xsd:sequence maxOccurs="unbounded" minOccurs="1">
								<xsd:element name="subLabel" type="cmn:simpleLabelType">
									<xsd:annotation>
										<xsd:documentation>Sub-label for legal use with the hosting main-label</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
				<xsd:attribute name="allowCompounds" type="xsd:boolean" use="optional">
					<xsd:annotation>
						<xsd:documentation>Flag to override global compound settings for this label</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="identifierTypeType">
		<xsd:annotation>
			<xsd:documentation></xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="cmn:simpleLabelType">
				<xsd:attribute name="uniqueness" type="wfl:uniquenessType">
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:simpleType name="uniquenessType">
        <xsd:annotation>
			<xsd:documentation>Constants usable for defining uniqueness of an identifier type</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="globally-unique">
				<xsd:annotation>
					<xsd:documentation>No external disambiguation needed, identifier is unique across all instances of RePlay-DH.</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="environment-unique">
				<xsd:annotation>
					<xsd:documentation></xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="locally-unique">
				<xsd:annotation>
					<xsd:documentation></xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="hash">
				<xsd:annotation>
					<xsd:documentation></xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="ambiguous">
				<xsd:annotation>
					<xsd:documentation></xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
    </xsd:simpleType>
    
</xsd:schema>

=== RePlay-DH/replay-dh-client/src/main/resources/bwfdm/replaydh/workflow/schema/default-schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rdh:workflowSchema xmlns:rdh="https://www.ub.uni-stuttgart.de/replay/Workflow" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.ub.uni-stuttgart.de/replay/Workflow Workflow.xsd"
	localizationRoot="replaydh.workflowSchema.default"
	useDefaultLocalizationSuffixes="true"
	localize="true"
	id="replaydh.workflow.schema.default"
	description="Basic schema developed in the context of computational linguistics and with resource types borrowed from DataCite kernel 4.0">

  <rdh:personIdentifiers allowCustomIdentifierTypes="true" defaultIdentifierType="name">
    <rdh:identifierType id="alias" uniqueness="ambiguous" localizationBase="alias"/>
    <rdh:identifierType id="name" uniqueness="ambiguous" localizationBase="name"/>
    <rdh:identifierType id="organization" uniqueness="ambiguous" localizationBase="organization"/>
    <rdh:identifierType id="local-name" uniqueness="environment-unique" localizationBase="localName"/>
    <rdh:identifierType id="firstname-lastname" uniqueness="ambiguous" localizationBase="firstnameLastname"/>
    <rdh:identifierType id="orcid" uniqueness="globally-unique" localizationBase="orcid"/>
    <rdh:identifierType id="homepage" uniqueness="globally-unique" localizationBase="homepage"/>
    <rdh:identifierType id="email" uniqueness="globally-unique" localizationBase="email"/>
    <rdh:identifierType id="address" uniqueness="globally-unique" localizationBase="address"/>
  </rdh:personIdentifiers>
  
  <rdh:resourceIdentifiers allowCustomIdentifierTypes="true" defaultIdentifierType="name-version">
    <rdh:identifierType id="name-version" uniqueness="ambiguous" localizationBase="nameVersion"/>
    <rdh:identifierType id="url" uniqueness="globally-unique" localizationBase="url"/>
    <rdh:identifierType id="path" uniqueness="locally-unique" localizationBase="path"/>
    <rdh:identifierType id="checksum" uniqueness="hash" localizationBase="checksum"/>
    <rdh:identifierType id="vlo-handle" uniqueness="globally-unique" localizationBase="vloHandle"/>
    <rdh:identifierType id="doi" uniqueness="globally-unique" localizationBase="doi"/>
    <rdh:identifierType id="rdh-id" uniqueness="environment-unique" localizationBase="rdhID"/>
    <rdh:identifierType id="group" uniqueness="locally-unique" localizationBase="group"/>
  </rdh:resourceIdentifiers>
  
  <!-- List of basic resource types borrowed from DataCite kernel 4.0 -->
  <rdh:resourceTypes allowCompoundLabels="true" allowCustomLabels="true" compoundSeparator="/" defaultLabel="dataset">
    <rdh:label id="audio-visual" localizationBase="audioVisual"/>
    <rdh:label id="collection" localizationBase="collection"/>
    <rdh:label id="dataset" localizationBase="dataset"/>
    <rdh:label id="event" localizationBase="event"/>
    <rdh:label id="image" localizationBase="image"/>
    <rdh:label id="interactive-object" localizationBase="interactiveObject"/>
    <rdh:label id="model" localizationBase="model"/>
    <rdh:label id="physical-object" localizationBase="physicalObject"/>
    <rdh:label id="service" localizationBase="service"/>
    <rdh:label id="software" localizationBase="software"/>
    <rdh:label id="sound" localizationBase="sound"/>
    <rdh:label id="text" localizationBase="text"/>
    <rdh:label id="workflow" localizationBase="workflow"/>
  </rdh:resourceTypes>
  
  <rdh:roles allowCompoundLabels="false" allowCustomLabels="true" defaultLabel="creator">
    <rdh:label id="annotator" localizationBase="annotator"/>
    <rdh:label id="operator" localizationBase="operator"/>
    <rdh:label id="curator" localizationBase="curator"/>
    <rdh:label id="editor" localizationBase="editor"/>
    <rdh:label id="creator" localizationBase="creator"/>
    <rdh:label id="consultant" localizationBase="consultant"/>
    <rdh:label id="principal-investigator" localizationBase="principalInvestigator"/>
    <rdh:label id="participant" localizationBase="participant"/>
  </rdh:roles>
  
</rdh:workflowSchema>
